### ISSUE TITLE
CTD when opening storages with countable items

### ISSUE THREAD

**Issue by Sephyros** [TheKrush/hafen-client#66]
Probably because of this https://github.com/dolda2000/hafen-client/commit/ee6487670b31d4b076d30c4a179130df428f2774
Error:

> java.lang.NoSuchMethodError: haven.GItem$Amount.<init>(Lhaven/ItemInfo$Owner;I)V
>     at Amount.build(amount.cjava:7)
>     at haven.ItemInfo.buildinfo(ItemInfo.java:364)
>     at haven.GItem.info(GItem.java:138)
>     at haven.WItem$AttrCache.get(WItem.java:154)
>     at haven.WItem.draw(WItem.java:286)
>     at haven.Widget.draw(Widget.java:711)
>     at haven.Widget.draw(Widget.java:716)
>     at haven.Inventory.draw(Inventory.java:73)
>     at haven.Widget.draw(Widget.java:711)
>     at haven.Widget.draw(Widget.java:716)
>     at haven.Window.draw(Window.java:255)
>     at haven.Widget.draw(Widget.java:711)
>     at haven.Widget.draw(Widget.java:716)
>     at haven.GameUI.draw(GameUI.java:845)
>     at haven.Widget.draw(Widget.java:711)
>     at haven.Widget.draw(Widget.java:716)
>     at haven.RootWidget.draw(RootWidget.java:124)
>     at haven.UI.draw(UI.java:156)
>     at haven.HavenPanel.rootdraw(HavenPanel.java:348)
>     at haven.HavenPanel.run(HavenPanel.java:628)
>     at java.lang.Thread.run(Unknown Source)

**Comment by TheKrush** [comment]
Does this also happen in Ender's client or just mine? I'm wondering if I messed up a merge.

**Comment by TheKrush** [comment]
Fixed with ee6487670b31d4b076d30c4a179130df428f2774
